### ISSUE TITLE
BasePresenter 中 parentFragment 需要 api >= 17

### ISSUE THREAD

**Issue by berial** [nekocode/kotlin_android_base_framework#10]
当全部使用 android.app.Fragment 时，它的 getParentFragment() 方法需要的 api 版本要大于等于 17。

**Comment by nekocode** [comment]
@Berial  是的，Kotlin 1.0.2 添加了 Android Lint Check 后才发现以前用了些高版本的 API，目前打算抽空改。

**Comment by berial** [comment]
而且如果用了 v4 的 Fragment，arguments(就是说的 bundle ) 关于 put 和 get 的 api 要求是 21，更加蛋疼。

**Comment by nekocode** [comment]
@Berial 不考虑 v4 了，之前尝试过，坑更多，。。
