### ISSUE TITLE
更完善的Fragment类库

### ISSUE THREAD

**Issue by ztc1997** [nekocode/kotlin_android_base_framework#11]
这是一个主要通过fragment构建ui的框架，然而提供的fragment类库是不是太simple了，许多原本activity上很简单的效果做起来相当麻烦，建议参考Fragmentation之类的fragment类库完善kotgo自带的fragment库，谢谢。

**Comment by nekocode** [comment]
这并不是一个主要通过 fragment 构建 ui 的框架。。框架强调的不是解决「使用单 activity 多 fragment 来构建 ui」的问题，这只是里面的一项辅助功能，想要更完善的功能本就应该使用更专职的第三方类库。

顺便问下，你说的「许多原本activity上很简单的效果做起来相当麻烦」是什么意思，能举个例子么？我会尽力完善。

**Comment by ztc1997** [comment]
@nekocode 例如转场动画，tab+多fragment就比较麻烦。
我试图结合一些其他的fragment类库使用，但是这些类库大多需要继承他的fragment和activity，而kotgo自带类库也需要，有没有可能让kotgo的类库不需要activity和fragment去继承，方便我们搭配其他的类库。

**Comment by nekocode** [comment]
@ztc1997 很抱歉目前来说并没有万全之策。你提到的 Fragmentation 本身也是框架型的类库，所以目前来说只能二选一。不过我会参考下它的代码继续完善这一块。
该 Issue 会保持打开状态，直到代码完善后关闭。

**Comment by nekocode** [comment]
@ztc1997 至于你提到的「让kotgo的类库不需要activity和fragment去继承」其实是也是可以实现的，不过对整个项目代码的改动会比较大（这样直接导致从框架降级为类库），所以我需要考虑下。

**Comment by wogenhaosini** [comment]
我比较赞同 @ztc1997 的看法，现有的fragment管理 我无法做到fragment嵌套fragmen的实现，这样项目中原有的fragment管理就鸡肋了。

**Comment by nekocode** [comment]
已去掉单 Activity 多 Fragment 架构。
