### ISSUE TITLE
RxLifecycle 的onDestroy 事件在View实现类里是不是发送的有点晚

### ISSUE THREAD

**Issue by 29995270** [nekocode/kotlin_android_base_framework#7]
比如fragment的onDetach 执行时， onDestroyView 已经触发了，视图被销毁后还没有取消订阅的话，会不会有风险

**Comment by nekocode** [comment]
@29995270 有道理，感谢提醒

**Comment by lozn00** [comment]
@29995270  您好，我想咨询一下   你能不能开发一个兼容水平和垂直的refreshlayout呀，  你的水平解决recyclerview的很叼，哈哈
